spring:
  autoconfigure:
    exclude: org.springframework.ai.autoconfigure.azure.openai.AzureOpenAiAutoConfiguration
  profiles:
    active: local
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  ai:
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: ai-embeddings
        use-tls: false
        initialize-schema: true
app:
  gen-ai:
    openai-client:
      key: ${OPEN_AI_KEY}
      endpoint: ${OPEN_AI_ENDPOINT}
      deployment-name: gpt-4o
    temperature: 0.8
    history-limit: 20
    non-text-models: dall-e-3,imagegeneration@005,stability.stable-diffusion-xl
    embedding:
      model: text-embedding-ada-002
      dimensions: 1536

external-clients:
  weather:
    url: https://api.weatherapi.com
    key: 05a3118aa3af4e3fbc2222604251201


